name: Android CI

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [main]
    paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    # container:
    #   image: docker://gradle:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
            distribution: 'zulu' # See Zulu OpenJDK
            java-version: '15'
      - run: java --version


      - name: gradle build
        run: ./gradlew build