name: Promote to internal testing

on:
  push:
    types: [closed]
    branches:
      - releases/**
  pull_request:
    types: [closed]
    branches:
      - releases/**
jobs:
  echo:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: echo
        run: echo "123"
    
  
